# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masage_note', models.CharField(max_length=200)),
                ('times_call', models.IntegerField(default=1)),
                ('date_call', models.DateTimeField(verbose_name='date call')),
                ('delta_time_call', models.DateTimeField(verbose_name='delta time cole')),
            ],
        ),
        migrations.DeleteModel(
            name='Timer',
        ),
    ]
