# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['must_complete_before']},
        ),
        migrations.AddField(
            model_name='note',
            name='complete_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='note',
            name='task',
            field=models.CharField(max_length=40),
        ),
    ]
