# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-13 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20170708_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_deream', models.CharField(max_length=40)),
                ('detail_deram', models.TextField(blank=True)),
                ('priority_dream', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
