# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-13 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_dream'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dream',
            options={'ordering': ['priority_dream']},
        ),
    ]
