# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-13 16:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_dream_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dream',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
