# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-24 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_auto_20170718_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='topdream',
            name='in_top',
            field=models.BooleanField(default=False),
        ),
    ]
