# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-29 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_topdream_in_top'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topdream',
            name='dreams',
        ),
        migrations.AddField(
            model_name='dream',
            name='in_top',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dream',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TopDream',
        ),
    ]
