# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-31 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_auto_20170729_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dream',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
